jquery/config/routes.rb
Jquery::Application.routes.draw do
  get "welcome/show"
  get 'welcome/autocomplete_brand_name'

  resources :products

  root :to => "welcome#show"

end

jquery/app/models/brand.rb
class Brand < ActiveRecord::Base
end

jquery/app/models/product.rb
class Product < ActiveRecord::Base
end

jquery/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

jquery/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  autocomplete :brand, :name

  def show
    @product = Product.new
  end

  def id_element_example
    @product = Product.new
  end

  def ajax_form_example

  end

  def show_the_form
    @product = Product.new
  end

  def formtastic
    @product = Product.new
  end

  autocomplete :brand_subtype, :name
  def subtype
    @product = Product.new
  end
end

jquery/app/helpers/application_helper.rb
module ApplicationHelper
end

jquery/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Jquey Auto complete" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui-1.8.2.custom.min.js', 'rails.js', 'autocomplete-rails.js' %>
    <%= stylesheet_link_tag 'jquery-ui-1.8.2.custom.css' %>
    
  </head>
  <body bgcolor="#CCCCCC" >
   
      <%#= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
  
  </body>
</html>

jquery/app/views/welcome/show.html.erb
<div style="background-color:#00CCFF">
<h1>jQuery Autocomplete</h1>
<%= form_for @product do |f| %>
  <%=f.label :brand_name %>
  <%=f.autocomplete_field :brand_name, welcome_autocomplete_brand_name_path %>  
  
<% end %>
<br/>
Ex:al


<br/>
<br/>
</div>